server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-auth
            uri: lb://user-service
            predicates:
              - Path=/api/auth/**
          - id: user-admin
            uri: lb://user-service
            predicates:
              - Path=/api/admin/**
          - id: user-profile
            uri: lb://user-service
            predicates:
              - Path=/api/user/**
          - id: song-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/songs/**