server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-auth
            uri: lb://user-service
            predicates:
              - Path=/api/auth/**
          - id: user-admin
            uri: lb://user-service
            predicates:
              - Path=/api/admin/**
          - id: user-profile
            uri: lb://user-service
            predicates:
              - Path=/api/user/**
          - id: user-static-files
            uri: lb://user-service
            predicates:
              - Path=/profilepic/**

          - id: song-service
            uri: lb://song-service
            predicates:
              - Path=/api/songs/**

          - id: like-service
            uri: lb://like-service
            predicates:
              - Path=/api/likes/**