server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-auth
            uri: lb://user-service
            predicates:
              - Path=/auth/**
          - id: user-admin
            uri: lb://user-service
            predicates:
              - Path=/admin/**
          - id: user-profile
            uri: lb://user-service
            predicates:
              - Path=/user/**
          - id: song-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/song/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka