server:
  port: 8083

spring:
  application:
    name: like-service

  datasource:
    url: jdbc:mysql://localhost:3306/like_service_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # change to validate in prod
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka